export const MODULES = [
  {
    id: "1",
    title: "Why Invest At All?",
    description: "Inflation, compound interest, and why keeping money in cash is a losing strategy",
    emoji: "💡",
    estimatedMinutes: 12,
    tier: "free",
    status: "available",
    path: "/module/1",
  },
  {
    id: "2",
    title: "The Building Blocks",
    description: "Stocks, bonds, ETFs, index funds — what they are and how they work",
    emoji: "🧱",
    estimatedMinutes: 14,
    tier: "paid",
    status: "available",
    path: "/module/2",
  },
  {
    id: "3",
    title: "How Markets Work",
    description: "Price discovery, bull and bear markets, crashes, and the long-term view",
    emoji: "📈",
    estimatedMinutes: 13,
    tier: "paid",
    status: "available",
    path: "/module/3",
  },
  {
    id: "4.1",
    title: "Know Yourself",
    description: "Discover your investor personality through 10 revealed-preference questions",
    emoji: "🧭",
    estimatedMinutes: 10,
    tier: "paid",
    status: "available",
    path: "/module/4-1",
  },
  {
    id: "4.2",
    title: "The Simulator",
    description: "Test your portfolio across 5 historical market crises",
    emoji: "🎮",
    estimatedMinutes: 15,
    tier: "paid",
    status: "available",
    path: "/module/4-2",
  },
  {
    id: "5",
    title: "Real-World Investing",
    description: "Brokerages, fees, time horizons, and the DCA challenge",
    emoji: "💼",
    estimatedMinutes: 15,
    tier: "paid",
    status: "available",
    path: "/module/5",
  },
  {
    id: "6.1",
    title: "Making Decisions — Analysis",
    description: "Qualitative vs quantitative analysis, moats, P/E ratio, market cap, EPS",
    emoji: "🔍",
    estimatedMinutes: 12,
    tier: "paid",
    status: "available",
    path: "/module/6-1",
  },
  {
    id: "6.2",
    title: "Making Decisions — Decisions",
    description: "Behavioural finance, common mistakes, and when to sell",
    emoji: "🧠",
    estimatedMinutes: 13,
    tier: "paid",
    status: "available",
    path: "/module/6-2",
  },
];